export const manifestoTitle = "MANİFESTOMUZ";
export const manifestoNav = "MANİFESTO";
export const manifestoTag = "#MAXİLEİLERİDÖNÜŞÜM";
export const manifestoText =
  " Algida Max ile ileri dönüşüm yolculuğu, her gün dondurmalarının tadına bakan milyonlarca kişiye dondurma çubuklarının atıktan uçağa, kalemliğe, kuş yuvasına ve daha onlarca fikre nasıl dönüşebilececeği konusunda ilham vermeyi amaçlar ve tüm ebeveyn ve çocuklarını daha sürdürülebilir bir dünya için ileri dönüşüm odağında OYUNA davet eder. ";
export const manifestoText2 =
  "Bir dondurma çubuğu sadece bir dondurma çubuğu değildir!";
export const manifestoText3 =
  "Haydi sen de ailecek bu dönüşüm yolculuğuna katıl, dondurma çubuklarını topla, dönüştür, paylaş ve herkese ilham ol!";
export const volunteerArtistHeader =
  "DondUrma ÇUbuĞU gÖNÜllÜ SanaTÇılarImızın eLİndE neLere dÖNÜŞtü MeraK edİyor musUn?";
export const volunteerArtistText =
  " Dondurma çubukları Onaranlar Kulübü gönüllü sanatçılarının elinde nelere dönüştü merak ediyorsan seni buraya alalım!";
export const discoverMore = "Hepsİne Göz At";
export const discoverAll = "Hepsİne Göz At";
export const discover = "Keşfet";
export const discoverHomeText =
  "İşte sizlerden gelen yaratıcı ileri dönüşüm projeleri!";
// export const FikirKutuphanesiHeader = "Aklına FİKİR GELMEDİ Mİ?";
export const FikirKutuphanesiText =
  "Aklına fikir gelmedi mi? O halde seni Onaranlar Kulübü’nün hazırladığı Fikir Kütüphanesi’ne davet ediyoruz!";
export const FikirKutuphanesiText2 =
  "Topladığın dondurma çubuklarının nelere dönüşebileceği konusunda sana fikir verecek ve yönlendirecek kılavuzlara buradan ulaşabilirsin!";
export const FikirKutuphanesiTitle = "FİKİR KÜTÜPHANESİ";
export const GonulluSanatcilarTitle = "Proje Sanatçıları";
export const ArtistsText = "Proje Sanatçılarının Eserlerİ";
export const yours = "Sizden Gelenler";
export const downloadText = "İNDİR!";
export const comingSoonText = "Çok Yakında Sizlerle!";
export const aboutProjectTitle = "Proje Hakkında";
export const sssTitle = "Sık Sorulan Sorular";
export const contactUs = " BİZE ULAŞıN";
export const privacyPolicy = "  GİZLİLİK POLİTİKASı";
export const aboutCookies = "ÇEREZLER HAKKıNDA BİLDİRİM";
export const kvkk = " KİŞİSEL VERİLERİN KORUNMASı";
export const legal = "Yasal";
export const unileverLegal = " © UNILEVER 2022 TÜM HAKLARI SAKLIDIR";
export const maxBlogTitle = "MaxBlog";
export const blogContentText1 =
  "Nüfusu giderek fazlalaşan ve bunun doğal bir sonucu olarak kaynakların yetersiz gelmeye başladığı küresel dünyamızın sürdürülebilirliği fazlasıyla önemli bir hal kazandı. Bugünkü şartlarda sürdürülebilirlik hareketinin yaygınlaştırılması için bireysel anlamda hayatımıza ekleyebileceğimiz birçok metot var. Bu metotlardan sadece bir tanesi halindeki ileri dönüşüm (upcycling), Algida Max ile başlattığımız hareketin odak noktasını oluşturuyor. Buna dair farkındalığın var ama nereden başlayacağına dair bir ilham mı arıyorsun? O zaman sana dünyanın birçok farklı yerinden yaratıcı ileri dönüşüm fikirleri ile yardım etmek isteriz! 😊";
export const blogContentText11 =
  " Hayatına ileri dönüşümü ilk kez 10 yıl önce bir restoranın kullanmadığı büyük zeytin tenekelerini evindeki küçük eşyaları depolamak yoluyla dahil eden Katarzyna Karolczyk, bu andan itibaren ürün tasarımı alanında lisans bitiren eşi Maciej ile ileri dönüşümde kullandıkları materyalleri çeşitlendirip kendi markasını olan “Karolchicks”’i kurmuş. Katarzyna’nın portföyünde, yaşadığı şehir olan Bochum’un futbol takımının da bağışlarıyla katkıda bulunduğu futbol toplarını çeşitli renklerdeki kablolarla beraber dönüştürdüğü avizeler yer alıyor. Katarzyna, futbol toplarının tekil katmanlarını anahtarlık; çoklu katmanlarını da kâse olarak dönüştürmeyi başarmış.";
export const blogContentText12 =
  "Sıradaki durağımız Brezilya, Rio de Janeiro. Rio de Janeiro merkezli ASTA’nın ana amacı tüm Brezilya’da kreatif bir şekilde faaliyet gösteren sanatçı ve grupları sürdürülebilir bir paydada buluşturmak. Platform bunu birçok farklı şirketin atık ve yan ürünlerini alıp bu materyalleri birçok farklı yaratıcı ile buluşturarak başarıyor. ASTA, sadece bu misyonla kendisini sınırlamıyor ve sürdürülebilirliğe katkıda bulunmak isteyen bireylere özel atölyeler yaparak insanların bu konudaki farkındalığını artırmaya çalışıyor. ASTA, bugüne kadar içinde elektronik atıklardan teneke içeceklerin kapaklarına kadar birçok materyali ileri dönüşüm ilkelerine uyarak dönüştürmüş halde. Bunların arasında Brezilya merkezli pazarlama ve iletişim ajansı Netza’nın yıl boyunca mekânlar ve reklamlar için kullandığı branda ve afişlerin fazlasıyla yapılan çantalardan tutun da disketlerden kalem kutusu yapımına kadar birçok ürün var. Bizce harika görünüyorlar";
export const blogContentText121 =
  "Son durağımız Avustralya, Yeni Güney Galler. Katarzyna ve Maciej çiftinin kurduğu Karolchicks markası gibi bir aile girişimi olan Hila, ileri dönüşüm kavramını zaman içerisinde biraz daha kurumsallaşarak uygulamaya başlamış. Avustralya merkezli girişim, daha çok atık camları ileri dönüşümle kazandırarak faaliyet gösteriyor. Atık camları servis tabakları, banyo seti, kolye ve mumluk gibi pek çok eşya halinde ileri dönüştüren Hila’nın ünü Avustralya dışına da taşmış halde. ";

export const blogContentText2 =
  "Jenerasyon X’ten Y’ye, Y’den Z’ye geçerken hayatlarımızda birçok değişiklik gerçekleşti. Teknolojiye erişim arttı, sosyal etkileşim biçimi değişti, genç neslin hayata bakış açısı ve değerleri bambaşka bir hal aldı. Değişen zamanın birçok getirisi ve birçok götürüsü olduğunun hepimiz farkındayız. Bu süreçte, yeni jenerasyonun en büyük eksikliklerinden biri çocukların sokakta oynayarak geçirdiği zaman oldu. Yeni nesil büyüklerinden hep şunu duydu: “Biz sizin yaşlarınızdayken sokaktan eve girmek istemezdik.” Sokakta oyuna erişilebilirliğin günden güne azalmasının da bu duruma etkisi büyük elbette. Öyle ki, 2018’de katıldığı Dünya Ekonomik Forumunda Lego Foundation yönetim kurulu başkanı John Goodwin, oyun oynamanın neslinin tükendiğini belirtiyor. Şöyle düşünüp baktığımızda Goodwin’in haksız olmadığını görebilirsiniz. Nesilden nesile aktarılan birçok alışkanlık olmasına rağmen sokakta oyun oynama alışkanlığı ne yazık ki günden güne azaldı. Ekonomik koşulların da dünya genelinde gerilemesi bu güzel mirasın yeni nesillere aktarılmasına ket vurdu. Tüm bu koşulları ele alarak durumu değiştirmek isteyen Anthill Creations, çocukların sokakta tekrar oynaması için elini taşın altına koyuyor.";
export const blogContentText21 =
  "Anthill Creations ekibi, çocuklar için oyunun ve oynamanın geleceğini değiştirmek isteyen bir grup mimarın bir araya gelmesiyle ortaya çıkan, kar amacı gütmeyen bir kuruluş. Oynamanın geleceğinin erişilebilirliğin artırılmasıya değişeceğine inanan ekip, her yıl binlerce oyun alanı inşa etmek istediğini dile getiriyor. Kurulduğu günden bu yana 283 alanı oyun parkına dönüştürdüklerini de belirtelim. Oynamayı erişilebilir kılmak amacıyla dört ana kavram üzerinde yoğunlaşan Anthill Creations, çalışmalarını gerçekleştirirken sosyal ve ekonomik koşulların yanı sıra yapılan işin çevreye etkisini de göz önünde bulunduruyor. Artık kullanılmayan alanları interaktif ve sürdürülebilir oyun alanlarına dönüştüren ekip kullandıkları geri dönüştürülmüş malzemeler ve ileri dönüştürülmüş oyun elemanları sayesinde alanın dönüşümünü daha hızlı ve ekonomik şekilde gerçekleştirebiliyor. Anthill Creations, çalışmalarının temelinde yatan dört ana kavramı şu şekilde özetliyor: ";
export const blogContentText22 =
  "AKamu - Bölgede yaşayanların artık kullanılmayan bir alanı tekrar hayata geçirmek için bir araya gelerek kamunun kamusal alanlara katkıda bulunması hedefleniyor.";
export const blogContentText23 =
  "İnteraktif - Özellikle çocukların sanal varoluşlarından uzaklaşması ve gerçek hayat etkileşiminin artırılması.";
export const blogContentText24 =
  "Öğrenme - Mekanın birebir bilgi aktarımını desteklemek üzere tasarlanması ve tasarlanan mekanın bu anlamda bir araç olarak kullanılması.";
export const blogContentText25 =
  " Çevre - Azalt, tekrar kullan ve geri kazandır pratiğinin uygulanması ile tüm yaş grupları için sürdürülebilir, uzun süreli ve etkisi yüksek deneyimlerin tasarlanması.";
export const blogContentText26 ="   İleri dönüşümü her projenin kalbinde tutan Anthill Creations ekibi, artık kullanılamayacak durumda olan eşyaların bir şekilde yeni bir amaca hizmet edebileceğini savunuyor. Dönüştürülen oyun alanlarında bu yaklaşmın örneklerini açıkça görebiliyoruz. En çok araba lastiklerini ve varilleri ileri dönüştüren ekibin tasarımlarına baktığımızda ortaya çıkan işlerin yaratcılığı ise göz dolduruyor. Rengarenk oyun parkurları, birbirinden güzel salıncaklar ve kaydıraklar bölgede yaşayan çocukların hemen ilgisini çekiyor. Düşük maliyetli, sürdürülebilir ve kurulumu hızlı olan bu oyun alanları ile eski alışkanlıkların tekrar gün yüzüne çıkması yüzleri gülümsetiyor. Oyunu geri getirerek oynamanın geleceğini değiştirmek isteyen ekip her yıl bünyesine yüzlerce gönüllü kazandırıyor. Gönüllülerin katkısı ve ekibin uzmanlığı sayesinde her yıl sayısız çocuk, önceki nesillerden kalan bu güzel mirası yaşatmaya devam ediyor.";
export const blogContentText3 =
  "Gezegen nüfusu artıkça ve ekonomik refah insanlar arasında paylaştırıldıkça doğal kaynak rezervleri bir noktadan sonra tehlike altına giriyor. Günümüzün hâkim ekonomik modeli doğrusal ürün üretme ve tüketme yöntemimiz, kırılgan ekosistemleri zedeleyerek değerli doğal kaynakların kaybına neden oluyor. Doğrusal model tüketim alışkanlıklarımızda bir dizi soruna yol açıyor:";
export const blogContentText31 =
  "Döngüsel ekonomi, ürünlerin daha uzun süre kullanıldığı ve malzemelerin yeni ürünler üretmek için yeniden tercih edildiği yerlerde daha sürdürülebilir çözümler getiriyor. Kaynaklar daha sorumlu bir şekilde ele alınarak ürün ömrü uzatılıyor ve herhangi bir atık üretmeden tüm malzemeler yeniden dolaşıma giriyor. ";
export const blogContentText32 =
  "Doğrusal Ekonomiden Döngüsel Ekonomiye    Çoğu malzeme her geri dönüştürüldüğünde değer kaybettiğinden, ürünün yeniden kullanımı, geri dönüşümden daha verimli oluyor. Bu nedenle, ürün ömrünü uzatmak, çevresel etkisini azaltmanın en iyi yolu olarak karşımıza çıkıyor. Döngüsel bir ekonomide ürünler dayanıklı, geliştirilebilir tamir edilebilir, depozitolu gibi seçeneklerle uzun ömürlü olacak şekilde karşımıza çıkıyor. Bu özellikler onları yeniden kullanım veya ikincil pazarlar için daha çekici hale getiriyor. Bu nedenle ürün ve malzeme ömrünün, tasarım aşamasında göz önünde bulundurulması gerekiyor. Ürün yaşam döngüsünün malzeme temini, üretimi, kullanılan ve yeniden kullanım aşamalarını göz önünde bulundurarak geri kazanım ve ileri dönüşüm seçenekleri değerlendirilebilir. Bunun için en önemli kriter tercih edilen ürünün ömrü olabilir. Hayatımızın her alanında yer alan bu ürünler, kullanım ömürlerinin sonunda yeni ürünler elde etmek için ihtiyaç duyulan değerli kaynaklara dönüşüyor. Böylece işlenmemiş malzemelerin kaynaklarından çıkarılması ihtiyacı en aza indirgeniyor. Hayatımızın her alanında bu disiplinle hareket etmek birçok süreçte ileri dönüşüm uygulamaları yaparak döngüsel ekonomiye katkı sunabileceğimiz anlamına geliyor. Biraz hayal gücü ve döngüsel pratikle ileri taşıyamayacağımız eylem yok!";
  export const blogContentText33 =
  "Doğrusal Ekonomiden Döngüsel Ekonomiye "
  export const blogContentText4 =
  "Üniversitenin ilk senesinde hastaneden dönüştürülen bir özel yurtta kalıyordum. Yemekhaneye inerken, merdivenleri çıkarken ya da koridorda kapı komşularımla sohbet ederken kullanım amacı değişikliğinin binanın ruhunu nasıl etkilediğini sık sık düşünürdüm. Belirsiz bekleyişler ile dolu hastane koridorları, artık bizim neşesi yüksek genç kız sohbetlerimizde kahkahalarla çınlıyordu."
  export const blogContentText41 =
  "Çevremizde gördüğümüz cansız nesnelerin nefes almıyor oluşu, onların birer ruha sahip olmadığını göstermiyor. Nasıl biz insanlar olarak varoluşumuzun başından beri amaçlarımızın peşinde koşuyorsak, yarattığımız beşeri unsurlar da bizden bağımsız bir şekilde çeşitli amaçlara hitap ediyor. Aynı zamanda biz her nasıl tecrübelerimizle karakter değişimi yaşıyorsak, hayatın gidişatı içinde nesnelerin veya yapıların da kullanım amaçları değişebiliyor. Kendimizden vazgeçmeden, daha iyi versiyonumuza ulaşmak için değişimi göze alabilirken; neden aynısını yarattıklarımız için de uygulayamayalım? Mimari ileri dönüşüm, kullanım amacını tamamlamış yapıların kucaklanarak yeni bir kimlik elde edinebilmesi için hem efektif hem de sürdürülebilir bir yol olarak görülüyor. "
  export const blogContentText42 =
  "Dünya gün geçtikçe yaşlanıyor fakat bize yaşamamız için sunduğu alan hep aynı. Hatta bugüne kadar O’nun kendine ayırdığı alanlardan çaldığımız kısımlar bizi milyonlarca yıldır sürdürülen yazısız anlaşmanın ağır çıktılarıyla yüzleştiriyor. Neyse ki son yıllarda yaşadığımız uyanış, talan ettiğimiz her şeyi onarmak için yaratıcı fırsatlar üretmemiz için bir çıkar yol ortaya koydu.    "
  export const blogContentText43 =
  "Dünyanın çeşitli yerlerinde yaratıcı zihinlere ilham olabilecek birçok mimari ileri dönüşüm örneği bulunuyor. Bakalım yeni kimliklerini kazanan yapıların kaç tanesinin geçmişini tahmin edebileceksin?  "
  export const blogContentText44 =
  "Bugün altı ana malzemenin (ahşap, tuğla, cam, beton, çelik, plastik) atıklarının %40’ı inşaat sektörü tarafından oluşturuluyor. Doğayı korumak ve sürdürülebilirliği merkeze almak için en popüler kavram geri dönüşüm gibi görünse de, biraz daha gölgede kalan ileri dönüşüm çok daha eğlenceli ve işlevsel sonuçlar ortaya koyabiliyor. Aynı zamanda yaratıcılığını ifade etmek için yoktan var etmek yerine değişimin öncüsü olmak isteyen sanatçıların kayda değer fikirleri, ileri dönüşüm ile ortaya hem estetik hem de değerini kaybetmeden geri kazanılmış ürünler çıkmasını sağlıyor. Ne de olsa eskimiş bir masayı yerinden kaldırabilirsiniz fakat söz konusu kullanılmayan bir fabrika olduğunda hem açığa çıkan atık hem de yok etmek için gereken enerji miktarı farklı çıkış yollarının tercih edilebilirliğini artırıyor. "
  export const RuhunuArayanYapılar =
  "Ruhunu arayan yapılar"
  export const yaraticiIcerik=
  "Yaratıcı İçerik Üretimi ve İleri Dönüşüm"
  export const zamansizIcerik=
  "Zamansız İçerikler"
  export const zenginIcgoru=
  "Zengin İçgörülere Sahip İçerikler"
  export const daimaGelisim=
  "Daima Gelişime Açık İçerikler"
  export const tekIcerik=
  "Tek İçerik, Sayısız Platform"
  export const upcycleAfrica =
  "Upcycle Africa"
  export const eTrash2Cash =
  "eTrash2Cash"
  export const asagiDonusum =
  "Aşağı Dönüşüm (Downcycle)"
  export const donguselEkonomi =
  "Döngüsel Ekonomi (Circular Economy)"
  export const ucR =
  "3R (Reducu, Reuse, Recycle)"
  export const ipucu =
  "Küçük bir ipucu: Tahminlerini mantık çerçevesi ile sınırlamamanı öneririz!  "
  export const blogBaslik1 =
  "Elbphilharmonie Hamburg, Herzog & de Meuron"
  export const blogBaslik2 =
  "Zeitz Afrika Çağdaş Sanat Müzesi, Heatherwick Studio"
  export const blogBaslik4 =
  "St. Ann’s Warehouse, Marvel Architects"
  export const blogBaslik5 =
  "CaixaForum Madrid, Herzog & de Meuron"
  export const blogBaslik6 =
  "Sant Francesc Manastırı, David Closes"
  export const blogContentText45 =
  "Elbphilharmonie (Elbe Filarmoni Salonu ya da Elphi) dünyanın en büyük ve akustik açıdan en gelişmiş konser salonlarından biri olarak karşımıza geliyor. Mimarlık firması Herzog & de Meuron tarafından ileri dönüşüm ile tasarlanan Elphi, önceki hayatında eski bir depo olan alt kısmının üzerine inşa edildi."
  export const blogContentText46 =
  "Endüstriyel mimarinin çağdaş sanat ile kesişiminin güzel bir çıktısı olan Zeitz Afrika Çağdaş Sanat Müzesi, mimari ileri dönüşüm konseptinin etkileyici örneklerinden biri. Şehrin simgelerinden biri haline gelen müze, geçmiş hayatında bir tahıl deposuydu. Binayı saran 42 tüpten oyulan müze yapısı, ziyaretçilerine görkemli bir atmosfer sunuyor."
  export const blogContentText47 =
  "Endüstriyel mimarinin çağdaş sanat ile kesişiminin güzel bir çıktısı olan Zeitz Afrika Çağdaş Sanat Müzesi, mimari ileri dönüşüm konseptinin etkileyici örneklerinden biri. Şehrin simgelerinden biri haline gelen müze, geçmiş hayatında bir tahıl deposuydu. Binayı saran 42 tüpten oyulan müze yapısı, ziyaretçilerine görkemli bir atmosfer sunuyor."
  export const blogContentText48 =
  "Brooklyn Köprüsü’nün dibine yer alan bir tütün deposu, bir gün St. Ann tiyatro topluluğuna ev sahipliği yapacağını tahmin edebilir miydi? Unutulmaya yüz tutmuş depo, Marvel Architects tarafından kompleks bir performans alanına dönüştürüldü. Sanatın hem sanat hem de toplum için birleştiği değerli örneklerden biri olduğunu söyleyebiliriz."
  export const blogContentText49 =
  "Bir müze ve kültür merkezi olarak değerlendirilen CaixaForum Madrid’ten bu kadar elektrik alıyor olmamızı geçmişte bir elektrik santrali olmasına bağlıyoruz. Elphi’ye de dokunan İsviçreli mimarlar, santral binasını hem yukarı hem aşağı genişleterek sanatseverlerin hizmetine sundu."
  export const blogContentText50 =
  "Kilisenin mimarı bütünlüğüne müdahale etmeyen Closes, sadece binanın hasarlı yüzeylerini onararak kültürel bir tesis ortaya koydu. Binanın hem dışına hem de içine yapılan ufak dokunuşlar, terk edilmiş bir binanın ufak bir ilgiyle neye dönüşebileceği konusunda güzel bir örnek teşkil ediyor. "
  export const algidaXonaranlar =
  "Bu proje Onaranlar Kulübü ve Algida Max'ın daha İYİ bir dünya inşa etme isteğiyle başladı ve senin katkılarınla büyüyor.";
export const blogContentText51 = "İnsanlığın ortak bilgi birikiminin tarihi çok eskilere dayansa da, bilgiye erişimimin hiçbir dönemde bulunduğumuz çağdaki kadar sınırsız olmadığı konusunda hemfikiriz. İnternetin icadından başlayarak tüm teknolojik gelişmeler ile bugüne kadar uzanan bu besleyici süreç, içerik tüketim alışkanlıklarımızın sık sık şekil değiştirmesine yol açıyor. Yeni platformlar, yeni akıllı cihazlar bir nevi markalara veya içerik üreticilere, tüketiciler ile iletişim kurmanın yeni yollarını gösteriyor. Blog yazılarının görsel içeriklere, görsel içeriklerin podcastlere dönüşümünü buna örnek olarak gösterebiliriz. Var olan herhangi bir ürünün bambaşka bir amaca hizmet ederek hayat bulmasına dayanan ileri dönüşüm, içerik sektöründe neden karşımıza çıkmasın ki?"
export const blogContentText52 = "Belki yazdığınız blog sayfasında en çok okunan yazı 6 aydır değişmiyor olabilir. Ya da içerik planlaması yaparken takvimi dolduracak yeni fikiler bulamıyor olabilirsin. Sürekli aynı konuya eğilmek her ne kadar kolaycılık gibi görünse de; içerik ileri dönüşümü bir fikirle yaratıcı olmanızı, alabileceğiniz tüm permütasyonları ve uzantıları hayal etmenizi gerekir. Eğer bunu sadece kolaya kaçmak gibi değerlendirip hızlı clickbait içerikler oluşturmaya yönelirsen, yalnızca günü kurtarmış olursun."
export const blogContentText53 = "Oysa iyi bir içerik her zaman şu özelliklerden beslenebilmelidir: Zamansızlık, zengin içgörülere sahip, daima gelişime açık."
export const blogContentText54 = "Gündemi kaçırmak artık hepimiz için kabus oldu. Belirli aralıklarla göz atılan sosyal medya hesapları, sık sık kontrol edilen kilit ekranları bilgiye erişimin verdiği özgürlüğün bizden neleri götürdüğünün bir ispatı. Ne de olsa geçmişte önemli olaylara yer veren ve ertesi güne kadar yenisine erişilemeyen gazetelerin insafındayken, şimdi dünyanın en ücra köşesinden bile anlık bilgi sağlayabiliyoruz. Söz konusu içerik ileri dönüşümü olduğunda, bu tarz hızlı içerikler pek de uygun adaylar sayılmazlar."
export const blogContentText55 = "Tam aksine Evergreen içerikler en temel konuları kapsayan ve işleyişe odaklanan içeriklerdir. Gündemden uzak olmalarıyla sürdürülebilir yapılarını korusalar da bu durum değişime açık olmadıkları anlamına gelmez. Temel konuları merkezine alan içeriklerin en parlak noktası daima hitap ettiğin kitle ile bağlantılı kalacak olmasıdır. Bu gücü reddetmeden döneminin şartlarına ve gelişmelerine bağlı olarak tekrar tekrar güncellemek, hem hedef kitle ile daima bağlantılı kalmayı hem de içeriklere dinamik ve yaratıcı bir yapı kazandırmayı sağlar."
export const blogContentText56 = "Bulunduğumuz çağda durdurulamaz bir hızla veri üretiyoruz. Statista’nın raporuna göre depoladığımız, tükettiğimiz ve ürettiğimiz toplam veri miktarı, 2020’den 2025’e kadar yıllık %19.2’lik bir artışla büyüyecek. Yani her geçen gün işleyebilmek için daha fazla veriye ve alana sahip oluyoruz."
export const blogContentText57 = "Dönem getirilerinin içerik karakterine vurduğu damgayı, günümüz içeriklerinin özünün verilere dayanmasından anlayabiliriz. Elimizdeki en büyük gücü en efektif şekilde kullanabilmek adına istatistikler, grafikler, çeşitli analizler gibi destekleyici detayı içeriklerimizin içine yerleştiriyoruz. Okuyucu için bir nevi güven unsuru haline gelen veri paylaşımları, ileri dönüşüm adına kullanılabilir. Denklem çok basit, bir içeriği ne kadar veriyle besliyorsanız o kadar güvenlidir. Bu güvenin getirdiği zamansızlığı arkamıza alarak, bir içeriği farklı bağlamlarda ve zamanlarda tekrar tekrar oluşturmamız mümkün."
export const blogContentText58 = "Bir içerik asla tükenmez. Neredeyse tamamı için bu çıkarımı yapabiliriz. Bir konuda her zaman konuşacak ve anlatacak şeyler bulabilirsin, ancak maharet bunları en başta iyi yerleştirmeyi bilmek ve daha sonradan nokta atışı analiz edebilmektedir."
export const blogContentText59 = "Başlıklar içeriğin gidişatına dair pek çok ipucu verir. Bir içerik oluştururken onu bölümlere ayırmak ve daima ileri dönüşüme açık kapı bırakacak kısımlar eklemek, önceki iki maddeyle de oldukça bağlantılı olacaktır. Nihayetinde bir ileri dönüşüm içeriği gelişime açık olmasıyla daima taze bilgiler ile zenginleştirilebilir ve bu da onu zamansız kılar."
export const blogContentText60 = "Hayatımızda profesyonel kariyerlerimizin haricinde ihtiyaç sahibi insanlara daha yakın olabilmek, onların potansiyellerini açığa çıkarmak için çalışmak ve toplumsal döngüde daha belirgin bir rol almalarını sağlamak için çoğumuz bir şekilde gönüllülük esasıyla çalışan sivil toplum kuruluşlarına dahil oluyoruz. Bu kuruluşların bazıları, belli imkansızlıklardan dolayı hayatın kenarında kalmış bireylere çeşitli yönlerle odaklanmaya çalışıyor. Dezavantajlı gruplara dahil bireylere ulaşmak adına kullanılan olgulardan nasibini alan bir diğer olgu ise hiç şüphesiz ki ileri dönüşüm. Gelin bu yazıda ileri dönüşüm üzerine çalışmalar yapan bazı kuruluşların dezavantajlı gruplara mensup bireyleri nasıl güçlendirdiğine bakalım…"
export const blogContentText61 = "2016 yılında Uganda merkezli kurulan “Upcycle Africa”, kreatif bir zihniyeti ön plana atarak plastik atıkların ileri dönüşümünü amaçlıyor. İlk başta çevre ile alakalı çoğu sivil toplum kuruluşunun fikirlerinden biri olarak görünen bu fikri diğer organizasyonlardan ayıran temel şey ise Afrika’daki temel sorunlardan biri olan genç işsizlere yeni bir meslek kazandırarak onları donanımlı bir hale getirip gelir elde etmelerini sağlamak. Upcycle Africa’nın hedef kitlesi sadece işsiz gençler değil, ayrıca genç yaşta anne olmak zorunda kalan kadınlar ve eşi hayatını kaybetmiş dullar da bu derneğin hedef kitlesi arasında."
export const blogContentText62 = "Upcycle Africa’nın alamet-i farikası plastik atık şişelerden yapılan çevre dostu evler. Toprak ile plastik şişelerini birleşiminden oluşan evler, maliyet açısından Uganda’daki insanlara uygun halde olmalarının yanı sıra depremlere karşı dayanıklı, ısıyı emen özelliğe de sahipler. Dernek, bugüne kadar beş ayrı topluluk içinde toplamda 108 kadına atık toplayıcılığı ile alakalı iş imkânı sunarken bu durum dezavantajlı gruplar içerisinde bulunan genç yaşta çocuk sahibi olan kadınların ekonomik bağımsızlığını kazanmasını sağlamış. Ekonomik bağımsızlıkları yönünden güçlenen kadınlardan düşük gelirli olanlar, bu şekilde çocuklarının okul masraflarına katkıda bulunabiliyorlar."
export const blogContentText63 = "Sahra altı Afrika’da gençlerin umutsuzluklarının tam ortasında duran “işsizlik” sorunu, stabil bir hayattan onları uzak tutmanın yanı sıra fakirlik olgusunu da güçlendiren bir durumken Upcycle Africa, varlığıyla yüzlerce gencin potansiyelini açığa çıkarmış durumdaydı ve altı yıldan bu yana bu sorunu olabildiğince azaltmak için bütün gücüyle uğraşıyor…"
export const blogContentText64 = "Geçtiğimiz yılın mayıs ayında başlayan kuzey Nijerya merkezli bu girişimin temel amacı da aslında Upcycle Africa ile benzeşiyorken ayrıldıkları temel yön, eT2C’nin Upcycle Africa’dan daha çok lokal topluluğa seslenmesi. Upcycle Africa gibi eT2C de düşük gelir seviyesindeki insanların günlük atıklarını ayrıştırarak gelir elde etmelerini teşvik ediyor. Proje, yaklaşık 120,000 insana sürdürülebilir atık yönetimi konusunda kökten bilgilendirmeyi amaçlıyor."
export const blogContentText65 = "Bauchi eyaletinde konumlanan girişim, sera gazı emisyonlarını başta plastik atıklar olmak üzere birçok türden atığı ileri dönüşümle tekrar hayata kazandırarak çevreye katkıda bulunmayı amaçlarken aynı anda düşük gelirli ve dezavantajlı gruplardan girişime katılan 200 kadını çeşitli atölyeler ile “Yeşil Elçiler” haline getirmeyi amaçlıyor. Ülkenin kuzeydoğusundaki en fakir eyaletlerden biri halindeki Bauchi’nin seçilmesindeki ana nedenlerden biri Nijerya’da 87 milyondan fazla kişinin günde 1 dolardan daha az bir gelir ile yaşamak zorunda olduğu gerçeği. Bu kadar düşük bir günlük gelir ile yaşamanın zorluğunu en şiddetli hissedenler ise savunmasız ve sınırlı eğitim birikimine sahip kadınlar."
export const blogContentText66 = "Sürecin işleyişi de kısaca şöyle: Programa katılan katılımcılar, kendi bölgelerinde üretilen plastik atıkları değerli yeniden kullanım araçlarına dönüştürmeyi öğreniyorlar. Öğretilen eğitim daha çok uygulama üzerine basit etkinliklerden oluşuyor. Örneğin pet şişe atıklarından üretilen bazı ev gereçleri arasında duvara asılı saatler, dokuma okul çantaları, cüzdanlar ve çiçek vazoları yer alıyor. Hedef kitleye mensup bireyler, ürettikleri bu eşyalardan gelir kazanırken mali yönden kendi ayakları üzerinde durmak için büyük bir adım atmış oluyorlar."
export const blogContentText70 = "İleri dönüşüm pratikleriyle atık maddelerin veya istenmeyen malzemelerin kullanılabilir bir ürüne dönüştürülerek değer elde edilmesi dünya çapında bir kazanım haline geldi. Çöpten toplanan malzemelerle inşa edilen binalar, hurdadan oluşturulan heykeller, bisiklete entegre edilmiş bir mutfak robotundan enerji elde edilmesi gibi sınırsız örnekler ileri dönüşümün aklımıza gelebilecek her yerde kullanılabileceği anlamına geliyor. Peki ileri dönüşüm ile birlikte haşır neşir olmaya başladığımız diğer başlıklar neler? Gelin birlikte kısa bir kavram haritası oluşturalım."
export const blogContentText71 = "Aşağı dönüşüm (Downcycle), geri dönüşüm uygulamalarından biridir. Yaygın olarak endüstriyel malzemelerde kullanılan bu ürünler geri dönüştürüldükçe değerlerini kaybederler. Böylece geri dönüştürülmüş formları tipik olarak orijinal özelliklerinden hem daha zayıf hem de daha ucuzdur. Örneğin beyaz yazı kağıdı genellikle kartona dönüştürülür, bir daha beyaz kağıt olarak kullanılamaz. Çünkü malzemeleri kullanılabilir bir şeye dönüştürmek için gereken ek kimyasallar ve enerji işlemleri yüksek bir maliyete neden olur. Bu süreçte geri dönüşüme tabi tutulan malzemeler daha düşük dereceli ürünlerle sonuçlanır."
export const blogContentText72 = "Döngüsel ekonomi, mevcut malzeme ve ürünleri mümkün olduğunca uzun süre paylaşmayı, kiralamayı, yeniden kullanmayı, onarmayı, ve geri dönüştürmeyi içeren bir üretim ve tüketim modelidir. Bu sayede ürünlerin yaşam döngüsü uzar. Günlük faaliyetlerde israfın en aza indirilmesi anlamına gelir. Bir ürün ömrünün sonuna ulaştığında, mümkün olan yerlerde ekonomi içinde tutulur. Bunlar tekrar tekrar üretken bir şekilde kullanılabilir ve böylece daha fazla değer yaratılabilir. Bu kavram, al-yap-tüket-at modeline dayanan geleneksel, doğrusal ekonomik modelden ayrılmaktadır. "
export const blogContentText73 = "3R kavramı atmak zorunda olduğumuz atık miktarını azaltmaya yardımcı olduğundan sürdürülebilir yaşamın önemli bir parçasını oluşturuyor. Bu süreçte ürettiğiniz atık miktarının azaltılması (reduce), malzemelerin mümkün olduğunca yeniden kullanılması (reuse) ve mümkün olan her ürünün geri dönüştürülmesi (recycle) benimseniyor. 3R ile atık malzemelerin bertaraf edildiği, alan kullanımının artırıldığı ve enerji kaybının en aza indirgendiği bir ekonomi yaratılıyor.  "
export const blogContentText74 = "Yaşadığımız dünyada yarattığımız atık miktarını en aza indirgeyebiliriz. İleri dönüşüm uygulamalarıyla elimizdeki malzemeleri birden fazla kez kullanabiliriz. Geri dönüşüm faaliyetleri ile bir ürünü atmak yerine kullanılabilir alt ürünlere dönüştürebiliriz. Tüm bunlar öncesinde yine yeni yeniden düşünmeliyiz. Eylemlerimizin çevresel boyutunu ve yine eylemlerimizle bu çevresel boyutun seyrini belirleyebiliriz!"


export const blogContentText591 = "İçerik ileri dönüşümü, yalnızca eski içeriklerden yeni ve dinamik içerikler üretmeye odaklanmaz. Bugün özellikle içerik pazarlamasında sosyal medya platformlarının gücüne başvuruyoruz. Bir blog yazısı kısaca özetlenip görsel materyallerle desteklenerek Instagram postuna, LinkedIn gönderisine ya da bir tweet’e dönüşebilir. Bu ileri dönüşümü sağlarken platform gerekliliklerini göz önünde bulundurmak, zaman ve enerjiden de tasarruf etmenizi sağlar. Birkaç basit örnekle sana başlangıç için ilham verebiliriz!"
export const madde1 = "1.	Blog içeriğinden podcast’e"
export const madde11 = "Metrobüste ayakta kalmaya çalışırken uzun metin yazıları okumak pek mümkün olmayabilir. Podcast’ler özellikle hareket gerektiren zorlu durumlarda içerik tüketimine efektif bir alternatif olarak karşımıza geliyor. Aynı içeriği seslendirip platforma yükleyebilir, konuya hakim bir konuk davet edebilir ya da yazıya dökmediğin detaylarla yepyeni bir ürün ortaya koyabilirsin. İleri dönüşüm hepimize tam teşekküllü bir özgürlük sunuyor, neden faydalanmayalım ki?"
export const madde2 = "2.	Blog içeriğinden bilgi grafiğine"
export const madde21 = "Yukarıda veri çağında olduğumuzdan ve verinin içeriklerimizin merkezine oturduğundan bahsetmiştik. Görselliğin gücünden sınırsız bir şekilde yararlanabildiğimiz bir çağda, blog içeriğini faydalı bir bilgi grafiğine dönüştürebilirsin. Üstelik bu sayede, içeriğin çevresinde gelişen konularda tekrar tekrar grafiğe yer verme şansına da sahip olursun. Ya da sosyal medyada yalnızca grafiğini paylaşarak insanların ilgisini konunun özüne toplayabilirsin. Tasarım uygulamalarından kolaylıkla oluşturabileceğin gibi çeşitli biçimlerde ve dosya türlerinde grafik oluşturmanı sağlayacak pek çok internet sitesi mevcut."
export const madde3 = "3.	Video içeriğinin 50 tonu"
export const madde31 = "Video içeriklerinin en iyi yönü hâlihazırda görsel içerik olmaları ve tüketiciyi harekete geçirme konusundaki yadsınamaz başarılarıdır. Bir konuyu veya olayı paylaşmaktan çok, bir hikaye anlatıyormuş havası yaratır. Bu nedenle de tüketimi eğlenceli ve kolaydır. Boşuna saatlerce aynı dizi ve filmlerde kitlenmiyoruz.Yalnızca konuyla direkt bağlantılı video içerikler değil, bu kategoriye ait olan her türlü unsur tekrar tekrar kullanılabilir. Örneğin Futurama’dan bir kesit bir teknoloji blogunun sosyal medyasını süsleyebilir. Ya da The Office’in bir sahnesi tüketicilerle bağ kurma adına tekrar tekrar kullanılabilir. Video içerikler kesilip, biçilip, farklı format ve bağlamlara sokularak sınırsız kullanıma ve farklı anlamlar ifade etmeye daima hazırdır."
export const madde4 = "4.	Haftalık bültenler"
export const madde41 = "Hafta boyu çalışıp didindin, harika içerikleri okuyucularla buluşturdun. Hafta bittiğinde onlara biz özet gönderip hafızalarını tazelemek istiyorsun. Bu doğrultuda hazırlanan bültenler, ileri dönüşüm sayesinde mevcut içeriklerin şekil değiştirerek tekrar gündeme oturmasına dayanıyor. İçeriğin yalnızca özünü alıp okuyucuyu blog sayfasına yönlendirecek şekilde detaylandırmak, ideal bir bülten hareketi diyebiliriz. Okuyucuyu ikna ettikten sonra her şey blog yazılarınızın kalitesine ve zamansızlığına kalıyor. Belki de çark tekrar tekrar başa dönüyordur ve ileri dönüşüm dinamikleri hepimizin ister istemez gözünün aradığı maddelerdir, kim bilir?"